title: ì§€ì—°ì´ì˜ githubê°œë°œë¸”ë¡œê·¸ ğŸ¶
description: "í”„ë¡œê·¸ë˜ë° ì§€ì‹ì„ ê³µìœ í•˜ëŠ” ì§€ì—°ì´ì˜ ê¹ƒí—ˆë¸Œ ê°œë°œë¸”ë¡œê·¸"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/me.png"

# Social Links
email: wldus23966@naver.com
github_username: GangJiyeon
youtube_username: twitter
blog_username: wldus23968
linkedin_username: linkedin

# External API
giscus_repo: "GangJiyeon/Gangjiyeon.github.io"
giscus_repoId: "R_kgDONkzylA"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDONkzylM4Cluu9"
goatcounter_code: 
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
